### ISSUE TITLE
Can whistle capture the request from serviceWorker?

### ISSUE THREAD

**Issue by JimmyVV** [avwo/whistle#187]
When I take some test with ServerWorker at local, I set some proxy rule like:

```
10.100.66.177 nearby.qq.com/nearby-index
``` 

there is a serviceWorker at nearby.qq.com/nearby-index/sw.js, when I browser `nearby.qq.com/nearby-index/index.html`, the sw's request couldn't be captured by whistle

Help~

**Comment by echopi** [comment]
hi JimmyVV:

whistle captures network request and proxy it. Only the network requests can be shown in the network panel . 

Your page may be cached and intercepted by sw.  You can check the `bypass for network` button, so that you can see all your page requests.

![image](https://user-images.githubusercontent.com/16034964/42932259-6944a9d2-8b74-11e8-9f25-b199629c297b.png)

**Comment by JimmyVV** [comment]
en, yeah. but that is not what I want to do. 

I mean, when i want to verify sw whether it could work normally or not by whistle, I find some requests couldn't be captured by whistle. 

so, could u give me a hand to solve this problem?

**Comment by echopi** [comment]
One thing we should be aware of is that the request response from the sw cache will not be captured by the whistle proxy. 

Try Chrome Devtools, it will show you all the requests even they are intercepted by sw.

**Comment by JimmyVV** [comment]
well... I don't care about the request which could be got from cacheStorage. That's my question:

```
These requests captured by sw,  only be fetched from network, could be they proxied by whistle?
```

**Comment by echopi** [comment]
The answer is yes

![image](https://user-images.githubusercontent.com/16034964/42983816-72721e02-8c1b-11e8-9a35-900f38d2aa7a.png)
